# Generated by Django 5.0.7 on 2024-08-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('merchant', 'Merchant')], default='driver', max_length=10),
            preserve_default=False,
        ),
    ]
