# Generated by Django 5.0.7 on 2024-08-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('driver', 'driver'), ('merchant', 'merchant'), ('admin', 'admin')], max_length=10),
        ),
    ]
