# Generated by Django 5.0.7 on 2024-08-16 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=9999999999, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$'), django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
            preserve_default=False,
        ),
    ]
