# Generated by Django 5.0.7 on 2024-08-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_adpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpreferences',
            name='metrad_opt_in',
            field=models.BooleanField(default=True),
        ),
    ]
