# Generated by Django 5.0.7 on 2024-08-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_adpreferences_metrad_opt_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpreferences',
            name='facebook_ads_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adpreferences',
            name='google_ads_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
