# Generated by Django 5.0.7 on 2024-08-20 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_adpreferences_facebook_ads_opt_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
