# Generated by Django 5.0.7 on 2024-08-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='age_range',
            field=models.CharField(choices=[('0-18', '0-18'), ('19-35', '19-35'), ('36-50', '36-50'), ('51+', '51+')], default='0-18', max_length=50),
        ),
        migrations.AlterField(
            model_name='ad',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='time_of_day',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=50, null=True),
        ),
    ]
