# Generated by Django 5.0.7 on 2024-08-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_age_range_alter_ad_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ad',
            name='age_range',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='time_of_day',
        ),
        migrations.AddField(
            model_name='ad',
            name='age_range',
            field=models.ManyToManyField(blank=True, to='ads.agerange'),
        ),
        migrations.AddField(
            model_name='ad',
            name='gender',
            field=models.ManyToManyField(blank=True, to='ads.gender'),
        ),
        migrations.AddField(
            model_name='ad',
            name='time_of_day',
            field=models.ManyToManyField(blank=True, to='ads.timeofday'),
        ),
    ]
