# Generated by Django 5.0.7 on 2024-08-05 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_agerange_gender_timeofday_remove_ad_age_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='maximum_budget',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AdAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_playtime', models.FloatField(default=0)),
                ('monthly_playtime', models.JSONField(default=dict)),
                ('last_played_at', models.DateTimeField(blank=True, null=True)),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='ads.ad')),
            ],
        ),
    ]
