# Generated by Django 5.0.7 on 2024-08-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_adpreferences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdPreferences',
        ),
    ]
