# Generated by Django 5.0.7 on 2024-08-22 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_budget_spendinghistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='budget',
            name='ad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ads.ad'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='budget',
            name='remaining_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
